title: "Timothy Maina"   # keep it simple
plugins:
  - jekyll-remote-theme # This is often included by default in GH Pages environments
  - jekyll-include-cache
remote_theme: "mmistakes/minimal-mistakes"
  
header_pages:
  - index.md
  - about.md
  - projects.md
